In [ ]:
import json
import pandas as pd
from huggingface_hub import login
login(token="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",add_to_git_credential=True)

In [ ]:
file_path = "datas/paper_review_data_longqlora_10pct(第二版的数据).jsonl"

In [ ]:
data_df = pd.DataFrame()
with open(file_path, 'r', encoding="utf-8") as f:
    for line in f:
        line_json = json.loads(line)
        data_df = pd.concat([
            data_df,
            pd.DataFrame({k:str(v) for k,v in line_json.items()},index=[0])  # index 给定 索引, 否则可能会报错
        ],
        ignore_index=True) # ignore_index 表示合并时忽略索引
data_df

In [ ]:
# 格式化输出一条input
print(data_df.iloc[1,0])

In [ ]:
# 格式化输出一条output
print(data_df.iloc[1,1])

In [ ]:
from transformers import AutoTokenizer
# 统计每条样本呢token的个数
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")
tokenizer

In [ ]:
# 测试一条
print(tokenizer(data_df.iloc[1,0],return_tensors=None))
print(len(tokenizer(data_df.iloc[1,0],return_tensors=None)["input_ids"]))

#### input token 统计

In [ ]:
# input token的个数
data_df["input_counts"] = data_df['input'].map(lambda x:len(
                                        tokenizer(x,return_tensors=None)['input_ids'])
                                        )
data_df

In [ ]:
# 查看token 数的分布
data_df['input_counts'].sort_values()

In [ ]:
# 查看分位数分布
data_df['input_counts'].quantile(q=[0.001, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 0.999, 1])

#### output token 统计

In [ ]:
data_df["output_counts"] = data_df['output'].map(lambda x:len(
                                        tokenizer(x,return_tensors=None)['input_ids'])
                                        )
data_df

In [ ]:
# 查看token 数的分布
data_df['output_counts'].sort_values()

In [ ]:
# 查看分位数分布
data_df['output_counts'].quantile(q=[0.001, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 0.999, 1])

#### input + output 的分布

In [ ]:
data_df['input_output_counts'] = data_df['input_counts'] + data_df['output_counts']
data_df

In [ ]:
# 查看token 数的分布
data_df['input_output_counts'].sort_values()

In [ ]:
# 查看分位数分布
data_df['input_output_counts'].quantile(q=[0.001, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 0.999, 1])

#### prompt 模版

In [ ]:
template = ("Below is an instruction that describes a task, paired with an input that provides further context. "
                "Write a response that appropriately completes the request.\n\n"
                "### Instruction:\n{{instruction}}\n\n### Input:\n{{input}}\n\n### Response:\n")  # # #
print(template)
print("="*200)
instruction = """You are a professional machine learning conference reviewer who reviews a given paper and considers 4 criteria: ** importance and novelty **, ** potential reasons for acceptance **, ** potential reasons for rejection **, and ** suggestions for improvement **. The "Input" is the given paper, and the "Response" is your review that you need to provide.\n\n\n""".strip()
print(instruction)
print("="*200)
template = template.replace("{{instruction}}", instruction)
print(template)

#### datasets

In [91]:
import datasets
file_path = "paper_review_data_longqlora_10pct(第二版的数据).jsonl"

/opt/homebrew/Caskroom/miniforge/base/envs/py3.10_ds_tranformers_4.39/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
dataset = datasets.load_dataset('json', 
                                        data_files={"train":file_path},
                                        num_proc=1
                                    )
dataset

In [ ]:
dataset['validation'] = dataset['train'].shuffle(42).select(range(50))
dataset

In [ ]:
dataset['train'].select(range(10))["input"]

In [ ]:
dataset['validation'].select(range(10))["input"]

#### torch 维度转化的一些基本函数的区别及用法

In [1]:
import torch
# from einops import rearrange

In [ ]:
a = torch.arange(16).reshape(1, 1, 4, 4)
a

In [ ]:
a.expand(2,3,-1,-1)

In [ ]:
a.repeat(2,3,1,1)

#### 维度变换验证

In [112]:
a = torch.arange(72).reshape(2, 4, 3*3)
a

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
         [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23, 24, 25, 26],
         [27, 28, 29, 30, 31, 32, 33, 34, 35]],

        [[36, 37, 38, 39, 40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59, 60, 61, 62],
         [63, 64, 65, 66, 67, 68, 69, 70, 71]]])

In [113]:
a = a.reshape(2,4,3,3)
print(a,a.shape)

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],

         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]],

         [[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]]],


        [[[36, 37, 38],
          [39, 40, 41],
          [42, 43, 44]],

         [[45, 46, 47],
          [48, 49, 50],
          [51, 52, 53]],

         [[54, 55, 56],
          [57, 58, 59],
          [60, 61, 62]],

         [[63, 64, 65],
          [66, 67, 68],
          [69, 70, 71]]]]) torch.Size([2, 4, 3, 3])


In [114]:
a = a.transpose(1,2)
a

tensor([[[[ 0,  1,  2],
          [ 9, 10, 11],
          [18, 19, 20],
          [27, 28, 29]],

         [[ 3,  4,  5],
          [12, 13, 14],
          [21, 22, 23],
          [30, 31, 32]],

         [[ 6,  7,  8],
          [15, 16, 17],
          [24, 25, 26],
          [33, 34, 35]]],


        [[[36, 37, 38],
          [45, 46, 47],
          [54, 55, 56],
          [63, 64, 65]],

         [[39, 40, 41],
          [48, 49, 50],
          [57, 58, 59],
          [66, 67, 68]],

         [[42, 43, 44],
          [51, 52, 53],
          [60, 61, 62],
          [69, 70, 71]]]])

In [115]:
a = a.transpose(1,2)
print(a,a.shape)

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],

         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]],

         [[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]]],


        [[[36, 37, 38],
          [39, 40, 41],
          [42, 43, 44]],

         [[45, 46, 47],
          [48, 49, 50],
          [51, 52, 53]],

         [[54, 55, 56],
          [57, 58, 59],
          [60, 61, 62]],

         [[63, 64, 65],
          [66, 67, 68],
          [69, 70, 71]]]]) torch.Size([2, 4, 3, 3])


In [116]:
a = a.reshape(4,2,3,3)
print(a,a.shape)

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],

         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]],


        [[[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]],

         [[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]]],


        [[[36, 37, 38],
          [39, 40, 41],
          [42, 43, 44]],

         [[45, 46, 47],
          [48, 49, 50],
          [51, 52, 53]]],


        [[[54, 55, 56],
          [57, 58, 59],
          [60, 61, 62]],

         [[63, 64, 65],
          [66, 67, 68],
          [69, 70, 71]]]]) torch.Size([4, 2, 3, 3])


In [117]:
a = a.transpose(1,2)
print(a,a.shape)

tensor([[[[ 0,  1,  2],
          [ 9, 10, 11]],

         [[ 3,  4,  5],
          [12, 13, 14]],

         [[ 6,  7,  8],
          [15, 16, 17]]],


        [[[18, 19, 20],
          [27, 28, 29]],

         [[21, 22, 23],
          [30, 31, 32]],

         [[24, 25, 26],
          [33, 34, 35]]],


        [[[36, 37, 38],
          [45, 46, 47]],

         [[39, 40, 41],
          [48, 49, 50]],

         [[42, 43, 44],
          [51, 52, 53]]],


        [[[54, 55, 56],
          [63, 64, 65]],

         [[57, 58, 59],
          [66, 67, 68]],

         [[60, 61, 62],
          [69, 70, 71]]]]) torch.Size([4, 3, 2, 3])


In [118]:
b = torch.arange(32).reshape(2,1,4,4)
print(b,b.shape)

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15]]],


        [[[16, 17, 18, 19],
          [20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31]]]]) torch.Size([2, 1, 4, 4])


In [119]:
print(b[:,:,:2,:2].repeat(2,1,1,1),b[:,:,:2,:2].repeat(2,1,1,1).shape)

tensor([[[[ 0,  1],
          [ 4,  5]]],


        [[[16, 17],
          [20, 21]]],


        [[[ 0,  1],
          [ 4,  5]]],


        [[[16, 17],
          [20, 21]]]]) torch.Size([4, 1, 2, 2])


#### index_select

In [126]:
c1 = b[:,:,:2,:2]
c1

tensor([[[[ 0,  1],
          [ 4,  5]]],


        [[[16, 17],
          [20, 21]]]])

In [127]:
c2 =b[:,:,2:4,2:4]
c2

tensor([[[[10, 11],
          [14, 15]]],


        [[[26, 27],
          [30, 31]]]])

In [128]:
e = torch.stack([c1,c2],dim=1)
print(e,e.shape)

tensor([[[[[ 0,  1],
           [ 4,  5]]],


         [[[10, 11],
           [14, 15]]]],



        [[[[16, 17],
           [20, 21]]],


         [[[26, 27],
           [30, 31]]]]]) torch.Size([2, 2, 1, 2, 2])


In [129]:
# 最终的分组mask
e = e.reshape(4,1,2,2)
print(e,e.shape)

tensor([[[[ 0,  1],
          [ 4,  5]]],


        [[[10, 11],
          [14, 15]]],


        [[[16, 17],
          [20, 21]]],


        [[[26, 27],
          [30, 31]]]]) torch.Size([4, 1, 2, 2])


In [130]:
e = e.expand(-1,3,-1,-1)
print(e,e.shape)

tensor([[[[ 0,  1],
          [ 4,  5]],

         [[ 0,  1],
          [ 4,  5]],

         [[ 0,  1],
          [ 4,  5]]],


        [[[10, 11],
          [14, 15]],

         [[10, 11],
          [14, 15]],

         [[10, 11],
          [14, 15]]],


        [[[16, 17],
          [20, 21]],

         [[16, 17],
          [20, 21]],

         [[16, 17],
          [20, 21]]],


        [[[26, 27],
          [30, 31]],

         [[26, 27],
          [30, 31]],

         [[26, 27],
          [30, 31]]]]) torch.Size([4, 3, 2, 2])


#### cat 与 stack区别: stack会增加一个维度

In [133]:
f = torch.cat([c1.unsqueeze(1),c2.unsqueeze(1)],dim=1)
print(f,f.shape)
print(f.reshape(4,1,2,2),f.reshape(4,1,2,2).shape)

tensor([[[[[ 0,  1],
           [ 4,  5]]],


         [[[10, 11],
           [14, 15]]]],



        [[[[16, 17],
           [20, 21]]],


         [[[26, 27],
           [30, 31]]]]]) torch.Size([2, 2, 1, 2, 2])
tensor([[[[ 0,  1],
          [ 4,  5]]],


        [[[10, 11],
          [14, 15]]],


        [[[16, 17],
          [20, 21]]],


        [[[26, 27],
          [30, 31]]]]) torch.Size([4, 1, 2, 2])


#### 滚动函数 roll

In [2]:
a = torch.arange(48).reshape(2, 2, 3, 4)
print(a,a.shape)

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]],


        [[[24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]],

         [[36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47]]]]) torch.Size([2, 2, 3, 4])


In [4]:
# head 维度后一半,沿着序列维度向左/向上滚动
a[:,1:] = a[:,1:].roll(-1,dims=2)
a

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[16, 17, 18, 19],
          [20, 21, 22, 23],
          [12, 13, 14, 15]]],


        [[[24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]],

         [[40, 41, 42, 43],
          [44, 45, 46, 47],
          [36, 37, 38, 39]]]])

#### 切块

In [1]:
import torch

In [6]:
a = torch.arange(12).reshape(3,4)   
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
a.chunk(2,dim=0)

(tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([[ 8,  9, 10, 11]]))

In [8]:
a.chunk(2,dim=1)

(tensor([[0, 1],
         [4, 5],
         [8, 9]]),
 tensor([[ 2,  3],
         [ 6,  7],
         [10, 11]]))

In [9]:
a = torch.arange(48).reshape(2, 2, 3, 4)
a

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]],


        [[[24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]],

         [[36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47]]]])

In [10]:
a.chunk(2,dim=2)

(tensor([[[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7]],
 
          [[12, 13, 14, 15],
           [16, 17, 18, 19]]],
 
 
         [[[24, 25, 26, 27],
           [28, 29, 30, 31]],
 
          [[36, 37, 38, 39],
           [40, 41, 42, 43]]]]),
 tensor([[[[ 8,  9, 10, 11]],
 
          [[20, 21, 22, 23]]],
 
 
         [[[32, 33, 34, 35]],
 
          [[44, 45, 46, 47]]]]))

In [11]:
torch.cat(a.chunk(2,dim=2),dim=2)

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]],


        [[[24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]],

         [[36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47]]]])